--table 1 : 게시판 테이블

  CREATE TABLE "TRIP"."BOARD" 
   (	"LIST_NUMBER" NUMBER(5,0), 
	"COUNTRY_NAME" VARCHAR2(50 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"BOARD_SUBJECT" VARCHAR2(100 BYTE), 
	"BOARD_SIGHT" VARCHAR2(200 BYTE), 
	"WRITE_DATE" DATE CONSTRAINT "WRITE_DATE_NN" NOT NULL ENABLE, 
	"WRITE_INDEX" VARCHAR2(2000 BYTE), 
	 PRIMARY KEY ("LIST_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MAMBER_NAME_FK" FOREIGN KEY ("MEMBER_NAME")
	  REFERENCES "TRIP"."MEMBER" ("MEMBER_NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--table 2 : 환율 코드 및 국가명 테이블
  
  CREATE TABLE "TRIP"."COUNTRY_CODE" 
   (	"COUNTRY_ID" VARCHAR2(10 BYTE), 
	"COUNTRY_NAME" VARCHAR2(30 BYTE) CONSTRAINT "COUNTRY_NAME_NN" NOT NULL ENABLE, 
	"CONTINENT" VARCHAR2(30 BYTE) CONSTRAINT "CONTINENT_NN" NOT NULL ENABLE, 
	"CURRENCY" VARCHAR2(10 BYTE) CONSTRAINT "COUNTRY_CURRENCY_NN" NOT NULL ENABLE, 
	"COUNTRY_LIST_NUMBER" NUMBER(3,0) CONSTRAINT "COUNTRY_LIST_NB_NN" NOT NULL ENABLE, 
	 PRIMARY KEY ("COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COUNTRY_NAME_UK" UNIQUE ("COUNTRY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--table 3 : 회원 정보 관련 테이블
  
  CREATE TABLE "TRIP"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(10 BYTE), 
	"MEMBER_PW" VARCHAR2(20 BYTE) CONSTRAINT "MEMBER_PW_NN" NOT NULL ENABLE, 
	"MEMBER_NAME" VARCHAR2(20 BYTE) CONSTRAINT "MEMBER_NAME_NN" NOT NULL ENABLE, 
	 PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEMBER_NAME_UK" UNIQUE ("MEMBER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--table 4 : 내 관심 여행지 저장 테이블
  
  CREATE TABLE "TRIP"."MY_SIGHT_LIST" 
   (	"USER_NAME" VARCHAR2(50 BYTE) CONSTRAINT "LIST_USER_NN" NOT NULL ENABLE, 
	"SIGHT_COUNTRY" VARCHAR2(100 BYTE) CONSTRAINT "LIST_SIGHT_COUNTRY_NN" NOT NULL ENABLE, 
	"SIGHT_NAME" VARCHAR2(200 BYTE) CONSTRAINT "LIST_SIGHT_NAME_NN" NOT NULL ENABLE, 
	"LIST_NUMBER" NUMBER(4,0) CONSTRAINT "LIST_NUMBER_NN" NOT NULL ENABLE, 
	 CONSTRAINT "LIST_NUMBER_UK" UNIQUE ("LIST_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


--table 5 : 관광지 리스트 테이블
  
  CREATE TABLE "TRIP"."SIGHT_LIST" 
   (	"SIGHT_COUNTRY_NAME" VARCHAR2(50 BYTE) CONSTRAINT "SIGHT_COUNTRY_NAME_NN" NOT NULL ENABLE, 
	"SIGHT_CONTINENT" VARCHAR2(20 BYTE) CONSTRAINT "SIGHT_CONTINENT_NN" NOT NULL ENABLE, 
	"SIGHT_NAME" VARCHAR2(200 BYTE) CONSTRAINT "SIGHT_NAME_NN" NOT NULL ENABLE, 
	"SIGHT_LOCATION" VARCHAR2(500 BYTE), 
	"SIGHT_OPENTIME" VARCHAR2(200 BYTE), 
	"SIGHT_INDEX" VARCHAR2(3000 BYTE), 
	"HIT" NUMBER(4,0) DEFAULT '0', 
	 CONSTRAINT "SIGHT_NAME_UK" UNIQUE ("SIGHT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

